version: "3"

services:
  app:
    build:
      context: .
      args:
        - NEXT_BUILD=0
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.next
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: yarn dev
